### ISSUE TITLE
Is the driving_model.h5 pretrained or openpilot's ?

### ISSUE THREAD

**Issue by MayDGT** [ASGuard-UCI/DRP-attack#3]
Hi, openpilot just gives the dlc files of three models, have you transformed dlc to .h5 or pretrained another model?

**Comment by tkm2261** [comment]
We have transformed the DLC model of OpenPilot v0.7.0 to .h5 Keras model. So, it is openpilot's model

**Comment by MayDGT** [comment]
> We have transformed the DLC model of OpenPilot v0.7.0 to .h5 Keras model. So, it is openpilot's model

Hi Takami, thanks for your reply! But are the weight parameters of the model directly from dlc or your training process? It seems that you build a model which has the same architecture as OpenPilot's driving model in models.py

**Comment by tkm2261** [comment]
It is directly from dlc since we do not have access to their training data. You can see the model architecture in DLC with SNPE SDK. We manually translate the model architecture to Keras one and validated it by checking outputs when feeding the same input. I think there is no automatic transformation from DLC to Keras. If you want to do it in a newer model, you also need to do it manually.

**Comment by MayDGT** [comment]
> It is directly from dlc since we do not have access to their training data. You can see the model architecture in DLC with SNPE SDK. We manually translate the model architecture to Keras one and validated it by checking outputs when feeding the same input. I think there is no automatic transformation from DLC to Keras. If you want to do it in a newer model, you also need to do it manually.

Thanks, Takami. So you feed the translated model and op's dlc model the same input, and check the outputs between them to generate the .h5 of the translated model?

**Comment by tkm2261** [comment]
yes
